openapi: 3.0.3
info:
  title: GRO.data Dataverse REST Access Metadatablocks API
  description: Native REST/search API for the GRO.data (Göttingen Research Online) Dataverse research-data repository operated by the Göttingen eResearch Alliance. Based on Dataverse 6.4.
  version: '6.4'
servers:
- url: https://data.goettingen-research-online.de/api
  description: GRO.data (Göttingen Research Online) Dataverse REST API
tags:
- name: Metadatablocks
paths:
  /metadatablocks:
    get:
      operationId: MetadataBlocks_listMetadataBlocks
      parameters:
      - name: onlyDisplayedOnCreate
        in: query
        schema:
          type: boolean
      - name: returnDatasetFieldTypes
        in: query
        schema:
          type: boolean
      responses:
        '200':
          description: OK
      tags:
      - Metadatablocks
  /metadatablocks/{identifier}:
    get:
      operationId: MetadataBlocks_getMetadataBlock
      parameters:
      - name: identifier
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
      tags:
      - Metadatablocks
